### ISSUE TITLE
Add attributes to the script tag using a filter

### ISSUE THREAD

**Issue by retrorism** [inpsyde/google-tag-manager#10]
**Is your feature request related to a problem? Please describe.**
Seeing how the combination GTM + UserCentrics seems to be quite common for cookie consent, I was wondering whether it would be reasonable to add a little integration to https://github.com/inpsyde/google-tag-manager to add a data-attribute to the script tag it renders. UserCentrics’ documentation asks for the following:
```
<script type="text/plain" data-usercentrics="Google Analytics">
(function(i,s,o,g,r,a,m){....} etc
</script>
```
**Describe the solution you'd like**
The documentation for the `wp_print_inline_script_tag()` suggests to use the `$attributes` in combination with the `wp_{inline}_script_attributes` filter but since there's no context being passed, I wouldn't know how we would prevent attributes added through a filter from being added to _other_ script tags that apply those filters. 
A custom filter like `inpsyde-google-tag-manager.script-attributes` would give developers full control over the attributes for the GTM script tag alone, with the added benefit that something like a nonce in the script tag (#7) also becomes a possibility.

**Describe alternatives you've considered**
- Rolling out a custom plugin that handles _all_ UserCentrics_ and GTM functionality is obviously not great. I think fixing it with an attributes filter is elegant and non-intrusive.

**Additional context**
UserCentrics docs: https://docs.usercentrics.com/#/direct-implementation-guide?id=step-2-adjust-existing-scripts

**Comment by Chrico** [comment]
It really looks like we cannot rely on the `wp_print_inline_script_tag`-filter which has no context to the current script and it's attributes. The only chance would be to have some identifier in the `$attributes`-array which is lateron printed out as well..So this makes no sense at all - but we can still use this function to be "future-proof".

I've implemented 2 new filters which allows you to filter the `$inlineScript` and the `$attributes`. See also: https://github.com/inpsyde/google-tag-manager/commit/e345f4442a54eab329a16ffe8d59ac9123f1124f

Please test and give some feedback @retrorism :)

**Comment by retrorism** [comment]
Awesom and definitely faster than I could've written a PR for the same functionality! Thanks, I'll test this now and let you know.

**Comment by retrorism** [comment]
@Chrico I can confirm that both filters work and that the attributes filter also provides a solution for (#7, CC @luislard). I did not do any intense try-to-break-it testing, though!

**Comment by Chrico** [comment]
Thanks for feedback. I'll try to make a release tomorrow, okay? :-)

**Comment by Chrico** [comment]
Version 1.6 was released with the new filters. :)
