### ISSUE TITLE
Add filters for additional Datalayers

### ISSUE THREAD

**Issue by retrorism** [inpsyde/google-tag-manager#13]
**Is your feature request related to a problem? Please describe.**
I always thought that the plugin already made it possible to add data from custom sources to the dataLayer, but - unless I'm mistaken - this is not the case. So an integration that needs different entries to be added to the dataLayer needs to render its own script tag with `dataLayer.push(['customKey','CustomValue'])`, where ideally, this happens in the same place.

**Describe the solution you'd like**
Two additional filters in the dataLayerProvider::boot method:
- one for an array to provide the dataCollectors (array of dataCollectorInterfaces)
- one for an array of settingsSpecs (array of settingsSpec arrays)
like so:

```
public function boot(GoogleTagManager $plugin)
    {
        $dataLayer = $plugin->get('DataLayer');

        $dataCollectors = apply_filters(
            'inpsyde.google-tag-manager.datalayer-data-collectors',
            [
                $plugin->get('DataLayer.User.UserDataCollector'),
                $plugin->get('DataLayer.Site.SiteInfoDataCollector')
            ]
        );

        foreach ($dataCollectors as $dataCollector) {
            $dataLayer->addData($dataCollector);
        }

        if (! is_admin()) {
            return;
        }

        $factory = $plugin->get('ChriCo.Fields.ElementFactory');

        $settings = apply_filters(
            'inpsyde.google-tag-manager.datalayer-data-collector-settings-specs',
            [
                $plugin->get('DataLayer')->settingsSpec(),
                $plugin->get('DataLayer.User.UserDataCollector')->settingsSpec(),
                $plugin->get('DataLayer.Site.SiteInfoDataCollector')->settingsSpec(),
            ]
        );

        $settingsPage = $plugin->get('Settings.Page');
        foreach ($settings as $spec) {
            $settingsPage->addElement(
                $factory->create($spec),
                $spec['filters'] ?? [],
                $spec['validators'] ?? []
            );
        }
    }
```
This way, a plugin that wants to add a compatible dataCollector can do so and optionally can add their own settings to the GTM settings panel.

**Describe alternatives you've considered**
- adding a filter to the datalayer script output (currently, only the attributes can be filtered): this may actually still be useful, but makes for a very hacky experience which seems unnecessary since all the interfaces to do this 'properly' are already provided by the plugin.
- refactoring the entire plugin to use inpsyde/modularity and so that it becomes possible to extend the dataLayerProvider (or whatever would be the best approach in that scenario 😏)

**Additional context**
Annoyingly, my usecase requires a bunch of things that are _almost_ provided by the default settings, just in a different format and wrapped inside an object.

**Comment by Chrico** [comment]
But thats already possible by hooking into the Plugin boostrap action and adding your own `Inpsyde\GoogleTagManager\DataLayer\DataCollectorInterface` to the `Inpsyde\GoogleTagManager\DataLayer\DataLayer`. 🤔 

```php
<?php
use Inpsyde\GoogleTagManager\GoogleTagManager;
use Inpsyde\GoogleTagManager\Event\BootstrapEvent;
use Inpsyde\GoogleTagManager\DataLayer\DataLayer;
use Inpsyde\GoogleTagManager\DataLayer\DataCollectorInterface;

add_action(
	BootstrapEvent::ACTION,
	static function(GoogleTagManager $gtm): void
	{
	
		$dataLayer = $gtm->get(DataLayer::class);
	
		$myData = new class implements DataCollectorInterface
		{
			public function isAllowed(): bool
			{
				return true;
			}

			public function data(): array 
			{
				return ['foo' => 'bar'];
			}
		}
		
	
		$dataLayer->addData($myData);
		
		// will produce:
		// dataLayer.push({'foo': 'bar'});
	}
);
```

**Comment by retrorism** [comment]
Ha! So I _did_ miss something. Thanks for pointing this out to me, I guess this issue can be closed then 😁
