### ISSUE TITLE
[Bug]: SettingsPage class is undefined

### ISSUE THREAD

**Issue by szepeviktor** [inpsyde/google-tag-manager#32]
### Description of the bug

https://github.com/inpsyde/google-tag-manager/blob/6697ec64b5a35a8e5ed9ad70fb14c56ff84c0880/src/Provider/SettingsProvider.php#L33-L38

### Reproduction instructions

use PHPStan

### Expected behavior

`class SettingsPage ...`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
Thanks 👍🏻 this has been fixed here: https://github.com/inpsyde/google-tag-manager/commit/4248493908a12891079af5f0538100ae947d8dea

**Comment by szepeviktor** [comment]
PHPStan has more "surprises" for you ...
