### ISSUE TITLE
[Bug]: Restore readme.txt

### ISSUE THREAD

**Issue by szepeviktor** [inpsyde/google-tag-manager#33]
### Description of the bug

https://github.com/inpsyde/google-tag-manager/blob/341f30a1aaed7291a7c054d45d7798009e4c2697/readme.txt

### Reproduction instructions

-

### Expected behavior

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
It's not a bug, it's a feature. :) The Plugin has been deprecated on WordPress.org and we're exclusively shipping it right now through GitHub.

**Comment by szepeviktor** [comment]
All right.
Maybe a mad scientist does `composer require inpsyde/google-tag-manager`
