### ISSUE TITLE
Add posibility to render the GTM script with the nonce

### ISSUE THREAD

**Issue by luislard** [inpsyde/google-tag-manager#7]
During a security check of one of the websites we were using this plugin SRI sub resource integrity and Content security policies were needed.

To be compliant gtm offers this solution -> https://developers.google.com/tag-manager/web/csp

We need a filter to be able to use the nonce version of the gtml loader script and a filter to pass a nonce when this option is active.

**Comment by Chrico** [comment]
Should be doable with https://github.com/inpsyde/google-tag-manager/issues/10#issuecomment-831910476 . :)

**Comment by Chrico** [comment]
I'm going to close this issue. With the latest 1.6 release this is now possible by using following filters:

```php
<?php
use Inpsyde\GoogleTagManager\Event

// Add attributes to the GTM <script>
add_filter(
	Event\GtmScriptTagRendererEvent::FILTER_SCRIPT_ATTRIBUTES,
	functions(array $attributes): array
	{
		
		$attributes['nonce'] = 'your-nonce';
		
		return $attributes;
	}
);


// Add attributes to the dataLayer <script>
add_filter(
	Event\DataLayerRendererEvent::FILTER_SCRIPT_ATTRIBUTES,
	functions(array $attributes): array
	{
		
		$attributes['nonce'] = 'your-nonce';
		
		return $attributes;
	}
);
```
